# Configuration Azure Foundry
AZURE_FOUNDRY_CHAT_ENDPOINT=https://<resource name>.cognitiveservices.azure.com/models
AZURE_FOUNDRY_CHAT_KEY=<API KEY>
AZURE_FOUNDRY_CHAT_MODEL=<model name>

AZURE_FOUNDRY_EMBED_ENDPOINT=https://<resource name>.cognitiveservices.azure.com/models
AZURE_FOUNDRY_EMBED_KEY=<API KEY>
AZURE_FOUNDRY_EMBED_MODEL=<model name>

spring.datasource.url=jdbc:postgresql://<your endpoint>:<port>/postgres
spring.datasource.username=<username>
spring.datasource.password=<password>
spring.jpa.hibernate.ddl-auto=none

# Paramètres RAG
RAG_TOP_K=5

# Limit file size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# Debug
logging.level.dev.langchain4j=DEBUG
logging.level.org.springframework.web=DEBUG
server.error.include-message=always
logging.level.java.net.http.HttpClient=DEBUG